# Generated by Django 2.2.6 on 2020-09-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0010_auto_20200901_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(height_field=200, null=True, upload_to='', width_field=100),
        ),
    ]
